"""Initial schema — frozen explicit ops (replaces the earlier dynamic
SQLModel.metadata.create_all bootstrap now that the model set is stable).
Future changes: `alembic revision --autogenerate -m "..."` for real diffs.
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kv',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capacity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capacity_set_day', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('capacity_set_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('setup_done', sa.Boolean(), nullable=False),
    sa.Column('last_checkin_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('agentlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentlog_agent'), 'agentlog', ['agent'], unique=False)
    op.create_index(op.f('ix_agentlog_day'), 'agentlog', ['day'], unique=False)
    op.create_index(op.f('ix_agentlog_user_id'), 'agentlog', ['user_id'], unique=False)
    op.create_table('energyevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energyevent_day'), 'energyevent', ['day'], unique=False)
    op.create_index(op.f('ix_energyevent_sync_version'), 'energyevent', ['sync_version'], unique=False)
    op.create_index(op.f('ix_energyevent_user_id'), 'energyevent', ['user_id'], unique=False)
    op.create_table('idea',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('raw', 'refining', 'klar', 'fail', name='ideastatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_day'), 'idea', ['day'], unique=False)
    op.create_index(op.f('ix_idea_sync_version'), 'idea', ['sync_version'], unique=False)
    op.create_index(op.f('ix_idea_updated_at'), 'idea', ['updated_at'], unique=False)
    op.create_index(op.f('ix_idea_user_id'), 'idea', ['user_id'], unique=False)
    op.create_table('shoppinglist',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slug', name='uq_shoppinglist_user_slug')
    )
    op.create_index(op.f('ix_shoppinglist_slug'), 'shoppinglist', ['slug'], unique=False)
    op.create_index(op.f('ix_shoppinglist_sync_version'), 'shoppinglist', ['sync_version'], unique=False)
    op.create_index(op.f('ix_shoppinglist_updated_at'), 'shoppinglist', ['updated_at'], unique=False)
    op.create_index(op.f('ix_shoppinglist_user_id'), 'shoppinglist', ['user_id'], unique=False)
    op.create_table('synctombstone',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'entity_id', name='uq_sync_tombstone')
    )
    op.create_index(op.f('ix_synctombstone_entity_id'), 'synctombstone', ['entity_id'], unique=False)
    op.create_index(op.f('ix_synctombstone_kind'), 'synctombstone', ['kind'], unique=False)
    op.create_index(op.f('ix_synctombstone_sync_version'), 'synctombstone', ['sync_version'], unique=False)
    op.create_index(op.f('ix_synctombstone_user_id'), 'synctombstone', ['user_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_index(op.f('ix_tag_user_id'), 'tag', ['user_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('essential', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('A', 'B', 'C', name='priority'), nullable=True),
    sa.Column('inbox', sa.Boolean(), nullable=False),
    sa.Column('synced_to_calendar', sa.Boolean(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('repeat_days', sa.JSON(), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_day'), 'task', ['day'], unique=False)
    op.create_index(op.f('ix_task_sync_version'), 'task', ['sync_version'], unique=False)
    op.create_index(op.f('ix_task_updated_at'), 'task', ['updated_at'], unique=False)
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    op.create_table('topic',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('centroid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_user_id'), 'topic', ['user_id'], unique=False)
    op.create_table('win',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_win_day'), 'win', ['day'], unique=False)
    op.create_index(op.f('ix_win_sync_version'), 'win', ['sync_version'], unique=False)
    op.create_index(op.f('ix_win_user_id'), 'win', ['user_id'], unique=False)
    op.create_table('capture',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('routed_type', sa.Enum('task', 'idea', 'shopping', name='capturetype'), nullable=True),
    sa.Column('routed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('topic_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capture_day'), 'capture', ['day'], unique=False)
    op.create_index(op.f('ix_capture_user_id'), 'capture', ['user_id'], unique=False)
    op.create_table('listitem',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('list_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['shoppinglist.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listitem_list_id'), 'listitem', ['list_id'], unique=False)
    op.create_index(op.f('ix_listitem_sync_version'), 'listitem', ['sync_version'], unique=False)
    op.create_index(op.f('ix_listitem_updated_at'), 'listitem', ['updated_at'], unique=False)
    op.create_index(op.f('ix_listitem_user_id'), 'listitem', ['user_id'], unique=False)
    op.create_table('taglink',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'entity_kind', 'entity_id', name='uq_taglink')
    )
    op.create_index(op.f('ix_taglink_day'), 'taglink', ['day'], unique=False)
    op.create_index(op.f('ix_taglink_entity_id'), 'taglink', ['entity_id'], unique=False)
    op.create_index(op.f('ix_taglink_entity_kind'), 'taglink', ['entity_kind'], unique=False)
    op.create_index(op.f('ix_taglink_tag_id'), 'taglink', ['tag_id'], unique=False)
    op.create_index(op.f('ix_taglink_user_id'), 'taglink', ['user_id'], unique=False)
    op.create_table('taskoccurrence',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('steps_snapshot', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'date', name='uq_task_occurrence_date')
    )
    op.create_index(op.f('ix_taskoccurrence_date'), 'taskoccurrence', ['date'], unique=False)
    op.create_index(op.f('ix_taskoccurrence_sync_version'), 'taskoccurrence', ['sync_version'], unique=False)
    op.create_index(op.f('ix_taskoccurrence_task_id'), 'taskoccurrence', ['task_id'], unique=False)
    op.create_index(op.f('ix_taskoccurrence_updated_at'), 'taskoccurrence', ['updated_at'], unique=False)
    op.create_index(op.f('ix_taskoccurrence_user_id'), 'taskoccurrence', ['user_id'], unique=False)
    op.create_table('taskstep',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskstep_sync_version'), 'taskstep', ['sync_version'], unique=False)
    op.create_index(op.f('ix_taskstep_task_id'), 'taskstep', ['task_id'], unique=False)
    op.create_index(op.f('ix_taskstep_updated_at'), 'taskstep', ['updated_at'], unique=False)
    op.create_index(op.f('ix_taskstep_user_id'), 'taskstep', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskstep_user_id'), table_name='taskstep')
    op.drop_index(op.f('ix_taskstep_updated_at'), table_name='taskstep')
    op.drop_index(op.f('ix_taskstep_task_id'), table_name='taskstep')
    op.drop_index(op.f('ix_taskstep_sync_version'), table_name='taskstep')
    op.drop_table('taskstep')
    op.drop_index(op.f('ix_taskoccurrence_user_id'), table_name='taskoccurrence')
    op.drop_index(op.f('ix_taskoccurrence_updated_at'), table_name='taskoccurrence')
    op.drop_index(op.f('ix_taskoccurrence_task_id'), table_name='taskoccurrence')
    op.drop_index(op.f('ix_taskoccurrence_sync_version'), table_name='taskoccurrence')
    op.drop_index(op.f('ix_taskoccurrence_date'), table_name='taskoccurrence')
    op.drop_table('taskoccurrence')
    op.drop_index(op.f('ix_taglink_user_id'), table_name='taglink')
    op.drop_index(op.f('ix_taglink_tag_id'), table_name='taglink')
    op.drop_index(op.f('ix_taglink_entity_kind'), table_name='taglink')
    op.drop_index(op.f('ix_taglink_entity_id'), table_name='taglink')
    op.drop_index(op.f('ix_taglink_day'), table_name='taglink')
    op.drop_table('taglink')
    op.drop_index(op.f('ix_listitem_user_id'), table_name='listitem')
    op.drop_index(op.f('ix_listitem_updated_at'), table_name='listitem')
    op.drop_index(op.f('ix_listitem_sync_version'), table_name='listitem')
    op.drop_index(op.f('ix_listitem_list_id'), table_name='listitem')
    op.drop_table('listitem')
    op.drop_index(op.f('ix_capture_user_id'), table_name='capture')
    op.drop_index(op.f('ix_capture_day'), table_name='capture')
    op.drop_table('capture')
    op.drop_index(op.f('ix_win_user_id'), table_name='win')
    op.drop_index(op.f('ix_win_sync_version'), table_name='win')
    op.drop_index(op.f('ix_win_day'), table_name='win')
    op.drop_table('win')
    op.drop_index(op.f('ix_topic_user_id'), table_name='topic')
    op.drop_table('topic')
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.drop_index(op.f('ix_task_updated_at'), table_name='task')
    op.drop_index(op.f('ix_task_sync_version'), table_name='task')
    op.drop_index(op.f('ix_task_day'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_tag_user_id'), table_name='tag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_synctombstone_user_id'), table_name='synctombstone')
    op.drop_index(op.f('ix_synctombstone_sync_version'), table_name='synctombstone')
    op.drop_index(op.f('ix_synctombstone_kind'), table_name='synctombstone')
    op.drop_index(op.f('ix_synctombstone_entity_id'), table_name='synctombstone')
    op.drop_table('synctombstone')
    op.drop_index(op.f('ix_shoppinglist_user_id'), table_name='shoppinglist')
    op.drop_index(op.f('ix_shoppinglist_updated_at'), table_name='shoppinglist')
    op.drop_index(op.f('ix_shoppinglist_sync_version'), table_name='shoppinglist')
    op.drop_index(op.f('ix_shoppinglist_slug'), table_name='shoppinglist')
    op.drop_table('shoppinglist')
    op.drop_index(op.f('ix_idea_user_id'), table_name='idea')
    op.drop_index(op.f('ix_idea_updated_at'), table_name='idea')
    op.drop_index(op.f('ix_idea_sync_version'), table_name='idea')
    op.drop_index(op.f('ix_idea_day'), table_name='idea')
    op.drop_table('idea')
    op.drop_index(op.f('ix_energyevent_user_id'), table_name='energyevent')
    op.drop_index(op.f('ix_energyevent_sync_version'), table_name='energyevent')
    op.drop_index(op.f('ix_energyevent_day'), table_name='energyevent')
    op.drop_table('energyevent')
    op.drop_index(op.f('ix_agentlog_user_id'), table_name='agentlog')
    op.drop_index(op.f('ix_agentlog_day'), table_name='agentlog')
    op.drop_index(op.f('ix_agentlog_agent'), table_name='agentlog')
    op.drop_table('agentlog')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_table('user')
    op.drop_table('kv')
    # ### end Alembic commands ###
