"""add settings_json to user

Revision ID: 486be798e250
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '486be798e250'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settings_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'settings_json')
    # ### end Alembic commands ###
