"""add checkin and calibration tables

Revision ID: 7f0a785be6ed
Revises: 486be798e250
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '7f0a785be6ed'
down_revision = '486be798e250'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('est', sa.Integer(), nullable=False),
    sa.Column('actual', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibration_sync_version'), 'calibration', ['sync_version'], unique=False)
    op.create_index(op.f('ix_calibration_user_id'), 'calibration', ['user_id'], unique=False)
    op.create_table('checkin',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('what', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thought', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kinder', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sync_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkin_sync_version'), 'checkin', ['sync_version'], unique=False)
    op.create_index(op.f('ix_checkin_user_id'), 'checkin', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkin_user_id'), table_name='checkin')
    op.drop_index(op.f('ix_checkin_sync_version'), table_name='checkin')
    op.drop_table('checkin')
    op.drop_index(op.f('ix_calibration_user_id'), table_name='calibration')
    op.drop_index(op.f('ix_calibration_sync_version'), table_name='calibration')
    op.drop_table('calibration')
    # ### end Alembic commands ###
